spring:
  application:
    name: AuthService

  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "Karan@123"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true